name: Build and Deploy (Self-Hosted)
 
on:
  push:
    branches: [main]
 
jobs:
  build-and-run:
    runs-on: self-hosted
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Debug: Arbeitsverzeichnis anzeigen
        run: |
          echo "PWD: $(pwd)"
          echo "--- Inhalt in src ---"
          ls -la src
          echo "--- Inhalt in src/CI_CD_Project_with_Unit_Tests ---"
          ls -la src/CI_CD_Project_with_Unit_Tests
          echo "--- Inhalt in src/CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests ---"
          ls -la src/CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests
 
      - name: Restore and Publish App
        run: |
          dotnet restore ./src/CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests.csproj
          dotnet publish ./src/CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests.csproj -c Release -o /home/azubi/deploy/csharp-app/
 
      - name: Restart App (optional)
        run: |
          systemctl --user restart my-csharp-app.service || echo "Service nicht vorhanden"