name: Build and Deploy (Self-Hosted)
 
on:
  push:
    branches: [main]
 
jobs:
  build-and-run:
    runs-on: self-hosted
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Zeige Arbeitsverzeichnis
        run: |
          pwd
          ls -la
 
      - name: Restore and Publish App
        run: |
           dotnet restore ./CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests.csproj
           dotnet publish ./CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests.csproj -c Release -o /home/azubi/deploy/csharp-app/
 
      - name: Restart App (optional)
        run: |
          systemctl --user restart my-csharp-app.service || echo "Service nicht vorhanden"