name: Build and Run pleaseeeeeeeeee

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build app
        run: msbuild CI_CD_Project_with_Unit_Tests\CI_CD_Project_with_Unit_Tests\CI_CD_Project_with_Unit_Tests.csproj /p:Configuration=Release

      - name: Check build output exists
        run: dir CI_CD_Project_with_Unit_Tests\CI_CD_Project_with_Unit_Tests\bin\Release\
        shell: powershell

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests/bin/Release/

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build

      - name: Upload to VM via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          source: "./build/"
          target: "~/deploy/csharp-app/"