name: Build and Run

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build app
        run: msbuild CI_CD_Project_with_Unit_Tests\CI_CD_Project_with_Unit_Tests.sln /p:Configuration=Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: CI_CD_Project_with_Unit_Tests\bin\Release\

  upload:
    name: Upload to Ubuntu Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build

      - name: Upload to VM via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          source: "./build/"
          target: "~/deploy/csharp-app/"

# on:
#   push:
#     branches: [main]

# jobs:
#   build-and-run:
#    runs-on: windows-latest

#    steps:
#     - name: Check code
#       uses: actions/checkout@v3

#     - name: Setup .NET
#       uses: actions/setup-dotnet@v3
#       with:
#         dotnet-version: '8.0.x'

#     - name: Upload Version
#       uses: 

#     - name: Install PuTTY tools (pscp)
#       run: choco install putty -y
#       shell: powershell

#     - name: Save SSH key to file
#       run: |
#         $key = "${{ secrets.VM_SSH_KEY }}"
#         $key | Out-File -FilePath "$env:USERPROFILE\.ssh\id_rsa" -Encoding ascii
#       shell: powershell

