name: Build and Run

on:
  push:
    branches: [main]

jobs:
  build-and-run:
   runs-on: ubuntu-latest

   steps:
    - name: Check code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore App
      run: dotnet restore ./CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests.csproj

    - name: Test App
      run: dotnet build ./CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests.csproj --no-restore


    - name: Run and Build App
      run: dotnet run ./CI_CD_Project_with_Unit_Tests/CI_CD_Project_with_Unit_Tests.csproj